#!/usr/bin/with-contenv bash

# Grab latest versions of the app
wget -O /bin/airupnp-arm https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-arm && chmod +x /bin/airupnp-arm
wget -O /bin/aircast-arm https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-arm && chmod +x /bin/aircast-arm

# Insert runtime commands if users has entered them as environment variables
[ -z "$AIRUPNP_VAR" ] || sed -i 's;command=/bin/airupnp-arm -l 1000:2000;command=/bin/airupnp-arm '"$AIRUPNP_VAR"';' /etc/supervisord.conf
[ -z "$AIRCAST_VAR" ] || sed -i 's;command=/bin/aircast-arm;command=/bin/aircast-arm '"$AIRCAST_VAR"';' /etc/supervisord.conf
